behaviors:
  PKWParking:
    trainer_type: poca
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0006
      beta: 0.005
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      conditioning_type: hyper
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 128
    summary_freq: 20000
    
environment_parameters:
  PKWParking_Parameters:
    curriculum:
      - name: DriveForwardLesson
        completion_criteria:
          measure: reward
          behavior: PKWParking
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 0.5
        value: 0
      - name: ReverseLesson
        completion_criteria:
          measure: reward
          behavior: PKWParking
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 0.5
        value: 1
      - name: BreakLesson
        completion_criteria:
          measure: reward
          behavior: PKWParking
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.6
        value: 2
      - name: TurnLesson
        value: 3
