behaviors:
  PKWParking:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0002
      beta: 0.015
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    checkpoint_interval: 500000
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
    keep_checkpoints: 10
    max_steps: 800000000
    time_horizon: 128
    summary_freq: 40000
    
environment_parameters:
  PKWParking_Parameters:
    curriculum:
      - name: DriveForwardLesson
        completion_criteria:
          measure: reward
          behavior: PKWParking
          signal_smoothing: true
          min_lesson_length: 250
          threshold: 0.2
        value: 0
      - name: ReverseLesson
        completion_criteria:
          measure: reward
          behavior: PKWParking
          signal_smoothing: true
          min_lesson_length: 500
          threshold: 0.39
        value: 1
      - name: TurnLesson
        completion_criteria:
          measure: reward
          behavior: PKWParking
          signal_smoothing: true
          min_lesson_length: 500
          threshold: 0.4
        value: 2
      - name: TurnLesson2
        completion_criteria:
          measure: reward
          behavior: PKWParking
          signal_smoothing: true
          min_lesson_length: 1000
          threshold: 0.42
        value: 3
      - name: FinalLesson
        value: 4
