behaviors:
  PKWParking:
    trainer_type: poca
    init_path: /home/attac1/Dokumente/Machine_Learning_Projekt/Self_Parking_MDRL/ML-Agents_Package/results/Versuch_4-1.4/PKWParking/PKWParking-1653863.pt
    hyperparameters:
      batch_size: 64
      buffer_size: 4096
      learning_rate: 0.00015
      beta: 0.001
      epsilon: 0.05
      lambd: 0.97
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 10
    even_checkpoints: false
    checkpoint_interval: 2000000
    max_steps: 25000000
    threaded: true
    time_horizon: 128
    summary_freq: 25000
    
environment_parameters:
  PKWParking_Parameters:
    curriculum:
      - name: Single1
        completion_criteria:
          measure: reward
          behavior: PKWParking
          signal_smoothing: true
          min_lesson_length: 250
          threshold: 0.45
        value: 0
      - name: Single2
        completion_criteria:
          measure: reward
          behavior: PKWParking
          signal_smoothing: true
          min_lesson_length: 250
          threshold: 0.5
        value: 1
      - name: DriveForwardLesson
        completion_criteria:
          measure: reward
          behavior: PKWParking
          signal_smoothing: true
          min_lesson_length: 250
          threshold: 0.4
        value: 2
      - name: ReverseLesson
        completion_criteria:
          measure: reward
          behavior: PKWParking
          signal_smoothing: true
          min_lesson_length: 250
          threshold: 0.45
        value: 3
      - name: TurnLesson
        completion_criteria:
          measure: reward
          behavior: PKWParking
          signal_smoothing: true
          min_lesson_length: 250
          threshold: 0.45
        value: 4
      - name: FinalLesson
        value: 5
