behaviors:
  PKWParking:
    trainer_type: poca
    hyperparameters:
      batch_size: 256
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.1
      lambd: 0.96
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 10
    even_checkpoints: false
    checkpoint_interval: 2000000
    max_steps: 25000000
    threaded: true
    time_horizon: 128
    summary_freq: 25000
    
environment_parameters:
  PKWParking_Parameters:
    curriculum:
      - name: DriveForwardLesson
        completion_criteria:
          measure: reward
          behavior: PKWParking
          signal_smoothing: true
          min_lesson_length: 250
          threshold: 0.33
        value: 0
      - name: ReverseLesson
        completion_criteria:
          measure: reward
          behavior: PKWParking
          signal_smoothing: true
          min_lesson_length: 250
          threshold: 0.5
        value: 1
      - name: TurnLesson
        completion_criteria:
          measure: reward
          behavior: PKWParking
          signal_smoothing: true
          min_lesson_length: 250
          threshold: 0.5
        value: 2
      - name: FinalLesson
        value: 3
