behaviors:
  PKWParking:
    init_path: /home/attac1/Dokumente/Machine_Learning_Projekt/Self_Parking_MDRL/ML-Agents_Package/results/Versuch_3-2.2/PKWParking/PKWParking-9999929.pt
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 4096
      learning_rate: 0.0002
      beta: 0.002
      epsilon: 0.25
      lambd: 0.96
      num_epoch: 4
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 10
    even_checkpoints: false
    checkpoint_interval: 2000000
    max_steps: 25000000
    threaded: true
    time_horizon: 128
    summary_freq: 25000
    
environment_parameters:
  PKWParking_Parameters:
    curriculum:
      - name: DriveForwardLesson
        completion_criteria:
          measure: reward
          behavior: PKWParking
          signal_smoothing: true
          min_lesson_length: 250
          threshold: 0.4
        value: 0
      - name: ReverseLesson
        completion_criteria:
          measure: reward
          behavior: PKWParking
          signal_smoothing: true
          min_lesson_length: 250
          threshold: 0.46
        value: 1
      - name: TurnLesson
        completion_criteria:
          measure: reward
          behavior: PKWParking
          signal_smoothing: true
          min_lesson_length: 250
          threshold: 0.45
        value: 2
      - name: FinalLesson
        value: 3
