default_settings: null
behaviors:
  PKWParking:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 4096
      learning_rate: 0.0002
      beta: 0.002
      epsilon: 0.25
      lambd: 0.96
      num_epoch: 4
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    checkpoint_interval: 2000000
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
    init_path: /home/attac1/Dokumente/Machine_Learning_Projekt/Self_Parking_MDRL/ML-Agents_Package/results/Versuch_3-2.2/PKWParking/PKWParking-9999929.pt
    keep_checkpoints: 10
    even_checkpoints: false
    max_steps: 25000000
    time_horizon: 128
    summary_freq: 25000
    threaded: true
    self_play: null
    behavioral_cloning: null
env_settings:
  env_path: build_1-3-2/iteration2
  env_args: null
  base_port: 5005
  num_envs: 1
  num_areas: 1
  timeout_wait: 60
  seed: -1
  max_lifetime_restarts: 10
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
  no_graphics_monitor: false
environment_parameters:
  PKWParking_Parameters:
    curriculum:
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 4075
          value: 0
      name: DriveForwardLesson
      completion_criteria:
        behavior: PKWParking
        measure: reward
        min_lesson_length: 250
        signal_smoothing: true
        threshold: 0.4
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 4076
          value: 1
      name: ReverseLesson
      completion_criteria:
        behavior: PKWParking
        measure: reward
        min_lesson_length: 250
        signal_smoothing: true
        threshold: 0.46
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 4077
          value: 2
      name: TurnLesson
      completion_criteria:
        behavior: PKWParking
        measure: reward
        min_lesson_length: 250
        signal_smoothing: true
        threshold: 0.45
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 4078
          value: 3
      name: FinalLesson
      completion_criteria: null
checkpoint_settings:
  run_id: Versuch_3-2.2
  initialize_from: null
  load_model: false
  resume: true
  force: false
  train_model: false
  inference: false
  results_dir: results
torch_settings:
  device: cuda
debug: false
